# Generated by Django 4.0.4 on 2022-04-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_list',
            name='cart_user_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
