# Generated by Django 4.0.4 on 2022-04-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_list_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_list',
            name='username',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
