# Generated by Django 4.0.4 on 2022-04-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_cart_list_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_list',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
