# Generated by Django 4.0.4 on 2022-04-20 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_cart_list_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_list',
            name='username',
        ),
    ]
